/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HallLazyImport = createFileRoute('/hall')()
const IndexLazyImport = createFileRoute('/')()
const GenreIndexLazyImport = createFileRoute('/genre/')()
const FilmIndexLazyImport = createFileRoute('/film/')()
const GenreTypeLazyImport = createFileRoute('/genre/$type')()
const FilmTitleLazyImport = createFileRoute('/film/$title')()

// Create/Update Routes

const HallLazyRoute = HallLazyImport.update({
  path: '/hall',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hall.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GenreIndexLazyRoute = GenreIndexLazyImport.update({
  path: '/genre/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/genre.index.lazy').then((d) => d.Route))

const FilmIndexLazyRoute = FilmIndexLazyImport.update({
  path: '/film/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/film.index.lazy').then((d) => d.Route))

const GenreTypeLazyRoute = GenreTypeLazyImport.update({
  path: '/genre/$type',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/genre.$type.lazy').then((d) => d.Route))

const FilmTitleLazyRoute = FilmTitleLazyImport.update({
  path: '/film/$title',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/film.$title.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/hall': {
      preLoaderRoute: typeof HallLazyImport
      parentRoute: typeof rootRoute
    }
    '/film/$title': {
      preLoaderRoute: typeof FilmTitleLazyImport
      parentRoute: typeof rootRoute
    }
    '/genre/$type': {
      preLoaderRoute: typeof GenreTypeLazyImport
      parentRoute: typeof rootRoute
    }
    '/film/': {
      preLoaderRoute: typeof FilmIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/genre/': {
      preLoaderRoute: typeof GenreIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  HallLazyRoute,
  FilmTitleLazyRoute,
  GenreTypeLazyRoute,
  FilmIndexLazyRoute,
  GenreIndexLazyRoute,
])

/* prettier-ignore-end */
